### PR TITLE
Data mapper

### PR DESCRIPTION
**Pull request by jthrilly**
Purpose of this PR is to implement a wrapper around prisma queries so that they are "safe", which means that they do not return unexpected data.

Motivation for this is that it is easy to accidentally pass sensitive info to client javascrtipt bundles in nextjs by passing the result of a prisma query into a client component. 

This PR also implements ES lint rule enforcement to make sure that the new pattern is followed.

Authored by @buckhalt.

### CODE REVIEW

**Comment by buckhalt** [comment]
This PR implements a data mapper, `safeLoader`, using `zod` for validation. This helps prevent security issues that come from fetching indiscriminately in Prisma.

This pattern is enforced with a custom eslint rule which requires instances of `prisma.*` to occur within a `safeLoader`. 


#CU-8685dzfhc

**Review by jabu404 — CHANGES_REQUESTED** [review]
Looks good to me, can we remove console.logs, though?

**Review by mrkarimoff — COMMENTED** [review]
It all looks good to me

**Comment by jthrilly** [comment]
Just a reminder to please use branch names like `feature/data-mapper`, `fix/horrible-bug`.

**Pull request merged**
